### ISSUE TITLE
It is not validating, if we have more than one variable.

### ISSUE THREAD

**Issue by iashanmugavel** [jeremywrowe/liquid-validator#2]
If we have more than one variable as an input and missed to close one variable tag then  it is not throwing false.

For example:

``` ruby
[1] pry(main)> input = "<p> {{name </p><p> {{description }}</p>"
=> "<p> {{name </p><p> {{description }}</p>"

[2] pry(main)> validator = LiquidValidator::Validator.new(input)
=> #<LiquidValidator::Validator:0x00000009ac8f60 @errors=[], @is_valid=true, @template="<p> {{name </p><p> {{description }}</p>">

[3] pry(main)> validator.valid?
=> true
```

**Comment by jeremywrowe** [comment]
Thanks for the report, I will take a look at it when I get a chance.

**Comment by jasdeepsingh** [comment]
@jeremywrowe have you had a chance to look at it?

**Comment by jeremywrowe** [comment]
No I haven't :)  This library has been unmaintained for some time, but I can revive it if that's helpful. I'll take a look in the next couple of days.

**Comment by jeremywrowe** [comment]
sorry for the delayed response, looking into it now. It looks like there are issues with newer versions of the liquid and the gem. I'm looking to remedy the problem as soon as I can. With the holiday season I've been extremely busy. Thanks for bringing the issue up again. Hopefully i'll find the time to fix it. If not pull requests are welcome.

**Comment by jeremywrowe** [comment]
Issue should be taken care of with version `1.0.1`
